<?php
    
    namespace Database\Factories\CustomProviders\en_NG;
    
    class NG_Custom_Person extends \Faker\Provider\Person
    {
        protected static $maleNameFormats = [
            '{{firstNameMale}} {{lastName}}',
            '{{firstNameMale}} {{firstNameMale}} {{lastName}}',
        ];
        
        protected static $femaleNameFormats = [
            '{{firstNameFemale}} {{lastName}}',
            '{{firstNameFemale}} {{firstNameFemale}} {{lastName}}',
        ];
        
        /**
         * An array of typical Nigerian male firstnames.
         *
         * @see https://andela-celisha-wigwe.github.io/names.html
         */
        protected static $firstNameMale = [
            'Abimbola', 'Wale', 'Abisoye', 'Adeboye', 'Adedayo', 'Adegoke', 'Akande', 'Akanni', 'Alade', 'Ayinde', 'Azubuike',
            'Banji', 'Bankole', 'Buchi', 'Bukola',
            'Chinedu', 'Chisom', 'Chukwu',
            'Damilare', 'Damilola', 'Danjuma',
            'Ebiowei', 'Emeka', 'Emmanuel',
            'Funmilade', 'Olufunso',
            'Gbeminiyi',
            'Ifeanyichukwu',
            'Ikenna', 'Ikhidie',
            'Johnson',
            'Kayode',
            'Aliyu',
            'Makinwa', 'Mohammed', 'Musa', 'Muyiwa',
            'Nnamdi',
            'Olaide', 'Olumide', 'Oluwunmi', 'Onoriode',
            'Remilekun', 'Rotimi',
            'Tari', 'Temitope', 'Tobiloba', 'Toke', 'Tomiloba',
            'Uzodimma',
            'Wale',
            'Yakubu', 'Yusuf',
        ];
        
        /**
         * @see https://andela-celisha-wigwe.github.io/names.html
         */
        protected static $firstNameFemale = array(
            'Abeni',
            'Adaugo',
            'Aminat',
            'Aminu',
            'Augustina',
            'Ayebatari',
            'Cherechi',
            'Chiamaka',
            'Chimamanda',
            'Chinyere',
            'Chizoba',
            'Ebiere',
            'Efe',
            'Fatima',
            'Ifeoma',
            'Ifunanya',
            'Isioma',
            'Jolayemi',
            'Faith',
            'Esther',
            'Funmi',
            'Adeola',
            'Lola',
            'Obioma',
            'Omawunmi',
            'Omolara',
            'Onome',
            'Rasheedah',
            'Sekinat',
            'Simisola',
            'Sumayyah',
            'Titi',
            'Titilayo',
            'Toluwani',
            'Zainab',
            "Abimbola",
            "Abosede",
            "Adeola",
            "Adepeju",
            "Adunni",
            "Anu",
            "Anu",
            "Ayinke",
            "Ayomide",
            "Ayoola",
            "Ayotunde",
            "Bimpe",
            "Biodun",
            "Bisi",
            "Blessing",
            "Bola",
            "Bolanle",
            "Bolu",
            "Bose",
            "Bukola",
            "Bukunmi",
            "Bunkunmi",
            "Bunmi",
            "Busayo",
            "Comfort",
            "Dabira",
            "Damilola",
            "Dammy",
            "Daniella",
            "Dara",
            "Darasimi",
            "Dayo",
            "Deborah",
            "Dolapo",
            "Dunmade",
            "Dunni",
            "Dunsi",
            "Ebun",
            "Elizabeth",
            "Eniola",
            "Enitan",
            "Esther",
            "Fadekemi",
            "Fehintola",
            "Feranmi",
            "Feyi",
            "Fisayo",
            "Fiyin",
            "Folade",
            "Folake",
            "Folake",
            "Foluke",
            "Fowoke",
            "Funke",
            "Funmbi",
            "Funmi",
            "Gbemi",
            "Grace",
            "Helen",
            "Ibidun",
            "Ibikun",
            "Ibironke",
            "Ife",
            "Ife",
            "Ige",
            "Inioluwa",
            "Ire",
            "Ireti",
            "Itunu",
            "Iyanu",
            "Iyin",
            "Joju",
            "Joke",
            "Jomiloju",
            "Jumoke",
            "Kemi",
            "Kike",
            "Kiki",
            "Labake",
            "Lade",
            "Lara",
            "Lola",
            "Lolade",
            "Mercy",
            "Mide",
            "Mobolade",
            "Moji",
            "Morayo",
            "Morenikeji",
            "Motunrayo",
            "Nike",
            "Odun",
            "Odunola",
            "Olamide",
            "Omorinsola",
            "Ope",
            "Oreofe",
            "Oyin",
            "Peju",
            "Praise",
            "Rejoice",
            "Remi",
            "Rike",
            "Ronke",
            "Ruth",
            "Sade",
            "Salewa",
            "Sewa",
            "Shade",
            "Simisola",
            "Sola",
            "Tade",
            "Tayo",
            "Teju",
            "Temi",
            "Tinuke",
            "Titi",
            "Tiwa",
            "Tobi",
            "Tola",
            "Tolu",
            "Tomi",
            "Toyin",
            "Tunmise",
            "Tutu",
            "Wemimo",
            "Wumi",
            "Wura",
            "Yejide",
            "Yemi",
            "Yetunde",
            "Yewande",
            "Yinka",
        );
        
        /**
         * @see https://andela-celisha-wigwe.github.io/names.html
         */
        protected static $lastName = [
            'Abiodun', 'Abiola', 'Abodunrin', 'Adebayo', 'Adegboye', 'Adegoke', 'Ademayowa', 'Ademola', 'Adeniyan', 'Adeoluwa', 'Aderinsola', 'Aderonke',
            'Adesina', 'Adewale', 'Adewunmi', 'Adewura', 'Adeyemo', 'Afolabi', 'Afunku', 'Agboola', 'Agnes', 'Aigbiniode', 'Ajakaiye', 'Ajose-adeogun', 'Akeem-omosanya',
            'Akerele', 'Akintade', 'Aligbe', 'Amaechi', 'Aremu', 'Atanda',
            'Babalola', 'Babatunde', 'Balogun', 'Bamisebi', 'Bello', 'Busari',
            'Chibike', 'Christian',
            'David',
            'Ebubechukwu', 'Egbochukwu', 'Ehigiator', 'Ekwueme', 'Elebiyo', 'Emmanuel',
            'Gbadamosi', 'Alabi', 'Aderinto', 'Rufai', 'Mohammed', 'Gbogboade', 'Isaac',
            'Ismail', 'Isokun', 'Iyalla',
            'Jamiu', 'Jimoh', 'Joshua', 'Justina',
            'Ladega', 'Lawal', 'Leonard',
            'Makuachukwu', 'Mobolaji', 'Mogbadunade', 'Motalo', 'Mukaram', 'Mustapha',
            'Ndukwu', 'Nojeem', 'Nwachukwu', 'Nwogu', 'Nwuzor',
            'Ogunbanwo', 'Ogunwande', 'Okonkwo', 'Okunola', 'Oladeji', 'Oladimeji', 'Olaoluwa',
            'Olasunkanmi', 'Olumide', 'Oluwanisola', 'Omobolaji', 'Onohinosen', 'Onose', 'Onyinyechukwu',
            'Opeyemi', 'Osuagwu', 'Oyebola', 'Oyelude',
            'Peter',
            'Saheed', 'Salami', 'Samuel', 'Sanusi', 'Segunmaru', 'Sulaimon',
            'Taiwo', 'Tamunoemi', 'Tella',
            'Uchechi',
            'Wasiu', 'Wilcox',
            'Yaqub', 'Yussuf',
        ];
    }
