<?php

namespace Database\Factories\CustomProviders\en_NG;

class NG_Custom_Address extends \Faker\Provider\Address
{
    protected static $postcode = ['#####', '## ###'];

    private static $county = [
        'Abuja', 'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra',
        'Bauchi', 'Bayelsa', 'Benue', 'Borno',
        'Cross River',
        'Delta',
        'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe',
        'Imo', 'Jigawa',
        'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
        'Lagos',
        'Nasarawa', 'Niger',
        'Ogun', 'Ondo', 'Osun', 'Oyo',
        'Plateau',
        'Rivers',
        'Sokoto',
        'Taraba',
        'Yobe',
        'Zamfara',
    ];

    protected static $country = [
        'Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica (the territory South of 60 deg S)', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
        'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island (Bouvetoya)', 'Brazil', 'British Indian Ocean Territory (Chagos Archipelago)', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
        'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo', 'Cook Islands', 'Costa Rica', 'Cote d\'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
        'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
        'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
        'Faroe Islands', 'Falkland Islands (Malvinas)', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories',
        'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana',
        'Haiti', 'Heard Island and McDonald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary',
        'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy',
        'Jamaica', 'Japan', 'Jersey', 'Jordan',
        'Kazakhstan', 'Kenya', 'Kiribati', 'Korea', 'Korea', 'Kuwait', 'Kyrgyz Republic',
        'Lao People\'s Democratic Republic', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
        'Macao', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
        'Namibia', 'Nauru', 'Nepal', 'Netherlands Antilles', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway',
        'Oman',
        'Pakistan', 'Palau', 'Palestinian Territories', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal', 'Puerto Rico',
        'Qatar',
        'Reunion', 'Romania', 'Russian Federation', 'Rwanda',
        'Saint Barthelemy', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia (Slovak Republic)', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard & Jan Mayen Islands', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
        'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
        'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'United States Minor Outlying Islands', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan',
        'Vanuatu', 'Venezuela', 'Vietnam',
        'Wallis and Futuna', 'Western Sahara',
        'Yemen',
        'Zambia', 'Zimbabwe',
    ];

    private static $regions = [
        "Abule Egba - Lagos",
        "Agege - Lagos",
        "Ajah - Lagos",
        "Alimosho - Lagos",
        "Amuwo Odofin - Lagos",
        "Apapa - Lagos",
        "Badagry - Lagos",
        "Egbe/Idimu - Lagos",
        "Ejigbo - Lagos",
        "Epe - Lagos",
        "Gbagada - Lagos",
        "Ibeju-Lekki - Lagos",
        "Iju - Lagos",
        "Ikeja - Lagos",
        "Ikorodu - Lagos",
        "Ikotun/Igando - Lagos",
        "Ikoyi - Lagos",
        "Ilupeju - Lagos",
        "Ipaja - Lagos",
        "Isolo - Lagos",
        "Ketu - Lagos",
        "Kosofe/Ikosi - Lagos",
        "Lagos Island - Lagos",
        "Lekki - Lagos",
        "Maryland - Lagos",
        "Mushin - Lagos",
        "Ogba - Lagos",
        "Ogudu - Lagos",
        "Ojo - Lagos",
        "Ojodu - Lagos",
        "Ojota - Lagos",
        "Okota - Lagos",
        "Orile - Lagos",
        "Oshodi - Lagos",
        "Sangotedo - Lagos",
        "Shomolu - Lagos",
        "Surulere - Lagos",
        "Victoria Island - Lagos",
        "Yaba - Lagos",
        "Apo - Abuja",
        "Asokoro - Abuja",
        "Central Area - Abuja",
        "Chika - Abuja",
        "Dakibiyu - Abuja",
        "Dakwo - Abuja",
        "Dape - Abuja",
        "Dei-Dei - Abuja",
        "Duboyi - Abuja",
        "Durumi - Abuja",
        "Gaduwa - Abuja",
        "Galadinmawa - Abuja",
        "Garki 1 - Abuja",
        "Garki 2 - Abuja",
        "Guzape - Abuja",
        "Gwagwa - Abuja",
        "Gwagwalada - Abuja",
        "Gwarinpa - Abuja",
        "Idu - Abuja",
        "Idu Industrial(Institution and Research) - Abuja",
        "Jabi - Abuja",
        "Jahi - Abuja",
        "Jukwoyi - Abuja",
        "Kabusa - Abuja",
        "Kado - Abuja",
        "Kafe - Abuja",
        "Karimu - Abuja",
        "Karmo - Abuja",
        "Karsana - Abuja",
        "Katampe Ext - Abuja",
        "Katampe Main - Abuja",
        "Kaura (Games Village) - Abuja",
        "Kubwa - Abuja",
        "Kuchigworro - Abuja",
        "Kuje - Abuja",
        "Kukwuaba - Abuja",
        "Kurudu - Abuja",
        "Life Camp - Abuja",
        "Lokogoma - Abuja",
        "Lugbe - Abuja",
        "Mabushi - Abuja",
        "Maitama - Abuja",
        "Mararaba - Abuja",
        "Mpape - Abuja",
        "Nbora - Abuja",
        "Nyanya - Abuja",
        "Orozo - Abuja",
        "Phase 1 - Abuja",
        "Phase 2 - Abuja",
        "Phase 3 - Abuja",
        "Pyakassa - Abuja",
        "Sub-Urban District - Abuja",
        "Utako - Abuja",
        "Wumba - Abuja",
        "Wuse 1 - Abuja",
        "Wuse 2 - Abuja",
        "Wuye - Abuja",
        "Abua-Odual - Rivers",
        "Ahoada West - Rivers",
        "Akuku-Toru - Rivers",
        "Andoni - Rivers",
        "Asari-Toru - Rivers",
        "Bonny - Rivers",
        "Degema - Rivers",
        "Eleme - Rivers",
        "Emohua - Rivers",
        "Etche - Rivers",
        "Gokana - Rivers",
        "Ikwerre - Rivers",
        "Khana - Rivers",
        "Obio-Akpor - Rivers",
        "Ogba-Egbema-Ndoni - Rivers",
        "Ogu-obolo - Rivers",
        "Okirika - Rivers",
        "Omuma - Rivers",
        "Opobo-Nkoro - Rivers",
        "Oyigbo - Rivers",
        "Port Harcourt - Rivers",
        "Tai - Rivers",
        "Abeokuta - Ogun",
        "Ado Odo/Ota - Ogun",
        "Agbara-Igbesa - Ogun",
        "Arepo - Ogun",
        "Ewekoro - Ogun",
        "Ifo - Ogun",
        "Ijebu - Ogun",
        "Obafemi Owode - Ogun",
        "Odogbolu - Ogun",
        "Ogun Waterside - Ogun",
        "Remo North - Ogun",
        "Sagamu - Ogun",
        "Yewa - Ogun",
        "Afijio - Oyo",
        "Akinyele - Oyo",
        "Atiba - Oyo",
        "Atisbo - Oyo",
        "Egbeda - Oyo",
        "Ibadan - Oyo",
        "Ibarapa - Oyo",
        "Ido - Oyo",
        "Irepo - Oyo",
        "Iseyin - Oyo",
        "Itesiwaju - Oyo",
        "Iwajowa - Oyo",
        "Kajola - Oyo",
        "Lagelu - Oyo",
        "Ogbomosho - Oyo",
        "Oyo - Oyo",
        "Surulere(Oyo) - Oyo",
        "Aguata - Anambra",
        "Anambra - Anambra",
        "Anambra East - Anambra",
        "Anambra West - Anambra",
        "Anaocha - Anambra",
        "Awka North - Anambra",
        "Awka South - Anambra",
        "Ayamelum - Anambra",
        "Dunukofia - Anambra",
        "Ekwusigo - Anambra",
        "Idemili North - Anambra",
        "Idemili south - Anambra",
        "Ihiala - Anambra",
        "Njikoka - Anambra",
        "Nnewi North - Anambra",
        "Nnewi South - Anambra",
        "Ogbaru - Anambra",
        "Onitsha North - Anambra",
        "Onitsha South - Anambra",
        "Orumba North - Anambra",
        "Orumba South - Anambra",
        "Oyi - Anambra",
        "Aninri - Enugu",
        "Enugu - Enugu",
        "Ezeagu - Enugu",
        "Igbo-Ekiti - Enugu",
        "Igbo-Eze South - Enugu",
        "IgboEze North - Enugu",
        "Isi-Uzo - Enugu",
        "Nkanu - Enugu",
        "Nkanu East - Enugu",
        "Nsukka - Enugu",
        "Oji-River - Enugu",
        "Udenu - Enugu",
        "Udi Agwu - Enugu",
        "Uzo-Uwani - Enugu",
        "Abak - Akwa Ibom",
        "Eastern Obolo - Akwa Ibom",
        "Eket - Akwa Ibom",
        "Esit Eket - Akwa Ibom",
        "Essien Udim - Akwa Ibom",
        "Etim Ekpo - Akwa Ibom",
        "Etinan - Akwa Ibom",
        "Ibeno - Akwa Ibom",
        "Ibesikpo Asutan - Akwa Ibom",
        "Ibiono Ibom - Akwa Ibom",
        "Ika - Akwa Ibom",
        "Ikono - Akwa Ibom",
        "Ikot Abasi - Akwa Ibom",
        "Ikot Ekpene - Akwa Ibom",
        "Ini - Akwa Ibom",
        "Itu - Akwa Ibom",
        "Mbo - Akwa Ibom",
        "Mkpat Enin - Akwa Ibom",
        "Nsit Atai - Akwa Ibom",
        "Nsit Ibom - Akwa Ibom",
        "Nsit Ubium - Akwa Ibom",
        "Obot Akara - Akwa Ibom",
        "Okobo - Akwa Ibom",
        "Onna - Akwa Ibom",
        "Oron - Akwa Ibom",
        "Oruk Anam - Akwa Ibom",
        "Udung Uko - Akwa Ibom",
        "Ukanafun - Akwa Ibom",
        "Uruan - Akwa Ibom",
        "Urue-Offong/Oruko - Akwa Ibom",
        "Uyo - Akwa Ibom",
        "Demsa - Adamawa",
        "Fufore - Adamawa",
        "Ganaye - Adamawa",
        "Gireri - Adamawa",
        "Gombi - Adamawa",
        "Guyuk - Adamawa",
        "Hong - Adamawa",
        "Jada - Adamawa",
        "Lamurde - Adamawa",
        "Madagali - Adamawa",
        "Maiha - Adamawa",
        "Mayo-Belwa - Adamawa",
        "Michika - Adamawa",
        "Mubi North - Adamawa",
        "Mubi South - Adamawa",
        "Numan - Adamawa",
        "Shelleng - Adamawa",
        "Song - Adamawa",
        "Toungo - Adamawa",
        "Yola North - Adamawa",
        "Yola South - Adamawa",
        "Aba - Abia",
        "Aba South - Abia",
        "Arochukwu - Abia",
        "Bende - Abia",
        "Ikwuano - Abia",
        "Isiala-Ngwa North - Abia",
        "Isiala-Ngwa South - Abia",
        "Isuikwato - Abia",
        "Ngwa - Abia",
        "Obi Nwa - Abia",
        "Ohafia - Abia",
        "Osisioma - Abia",
        "Ugwunagbo - Abia",
        "Ukwa East - Abia",
        "Ukwa West - Abia",
        "Umu-Neochi - Abia",
        "Umuahia North - Abia",
        "Umuahia South - Abia",
        "Alkaleri - Bauchi",
        "Bauchi - Bauchi",
        "Bogoro - Bauchi",
        "Damban - Bauchi",
        "Darazo - Bauchi",
        "Dass - Bauchi",
        "Ganjuwa - Bauchi",
        "Giade - Bauchi",
        "Itas/Gadau - Bauchi",
        "Jama'are - Bauchi",
        "Katagum - Bauchi",
        "Kirfi - Bauchi",
        "Misau - Bauchi",
        "Ningi - Bauchi",
        "Shira - Bauchi",
        "Tafawa-Balewa - Bauchi",
        "Toro - Bauchi",
        "Warji - Bauchi",
        "Zaki - Bauchi",
        "Brass - Bayelsa",
        "Ekeremor - Bayelsa",
        "Kolokuma/Opokuma - Bayelsa",
        "Nembe - Bayelsa",
        "Ogbia - Bayelsa",
        "Sagbama - Bayelsa",
        "Southern Jaw - Bayelsa",
        "Yenegoa - Bayelsa",
        "Ado - Benue",
        "Agatu - Benue",
        "Apa - Benue",
        "Buruku - Benue",
        "Gboko - Benue",
        "Guma - Benue",
        "Gwer East - Benue",
        "Gwer West - Benue",
        "Katsina-Ala - Benue",
        "Konshisha - Benue",
        "Kwande - Benue",
        "Logo - Benue",
        "Makurdi - Benue",
        "Obi - Benue",
        "Ogbadibo - Benue",
        "Ohimini - Benue",
        "Oju - Benue",
        "Okpokwu - Benue",
        "Oturkpo - Benue",
        "Tarka - Benue",
        "Ukum - Benue",
        "Ushongo - Benue",
        "Vandeikya - Benue",
        "Abadam - Borno",
        "Askira/Uba - Borno",
        "Bama - Borno",
        "Bayo - Borno",
        "Biu - Borno",
        "Chibok - Borno",
        "Damboa - Borno",
        "Dikwa - Borno",
        "Gubio - Borno",
        "Guzamala - Borno",
        "Gwoza - Borno",
        "Hawul - Borno",
        "Jere - Borno",
        "Kaga - Borno",
        "Kala/Balge - Borno",
        "Konduga - Borno",
        "Kukawa - Borno",
        "Kwaya Kusar - Borno",
        "Mafa - Borno",
        "Magumeri - Borno",
        "Maiduguri - Borno",
        "Marte - Borno",
        "Mobbar - Borno",
        "Monguno - Borno",
        "Ngala - Borno",
        "Nganzai - Borno",
        "Shani - Borno",
        "Abi - Cross River",
        "Akamkpa - Cross River",
        "Akpabuyo - Cross River",
        "Bakassi - Cross River",
        "Bekwara - Cross River",
        "Biase - Cross River",
        "Boki - Cross River",
        "Calabar - Cross River",
        "Etung - Cross River",
        "Ikom - Cross River",
        "Obanliku - Cross River",
        "Obudu - Cross River",
        "Odubra - Cross River",
        "Odukpani - Cross River",
        "Ogoja - Cross River",
        "Yala - Cross River",
        "Yarkur - Cross River",
        "Aniocha - Delta",
        "Aniocha South - Delta",
        "Asaba - Delta",
        "Bomadi - Delta",
        "Burutu - Delta",
        "Ethiope East - Delta",
        "Ethiope West - Delta",
        "Ika North-East - Delta",
        "Ika South - Delta",
        "Isoko North - Delta",
        "Isoko south - Delta",
        "Ndokwa East - Delta",
        "Ndokwa West - Delta",
        "Okpe - Delta",
        "Oshimili - Delta",
        "Oshimili North - Delta",
        "Patani - Delta",
        "Sapele - Delta",
        "Udu - Delta",
        "Ughelli North - Delta",
        "Ughelli South - Delta",
        "Ukwani - Delta",
        "Uvwie - Delta",
        "Warri - Delta",
        "Abakaliki - Ebonyi",
        "Afikpo - Ebonyi",
        "Ebonyi - Ebonyi",
        "Ezza - Ebonyi",
        "Ezza South - Ebonyi",
        "Ishielu - Ebonyi",
        "Ivo - Ebonyi",
        "lkwo - Ebonyi",
        "Ohaozara - Ebonyi",
        "Ohaukwu - Ebonyi",
        "Onicha - Ebonyi",
        "Central - Edo",
        "Egor - Edo",
        "Esan Central - Edo",
        "Esan North-East - Edo",
        "Esan South-East - Edo",
        "Esan West - Edo",
        "Etsako Central - Edo",
        "Etsako East - Edo",
        "Igueben - Edo",
        "Oredo - Edo",
        "Orhionwon - Edo",
        "Ovia South-East - Edo",
        "Ovia SouthWest - Edo",
        "Uhunmwonde - Edo",
        "Ukpoba - Edo",
        "Ado-Ekiti - Ekiti",
        "Efon - Ekiti",
        "Ekiti South-West - Ekiti",
        "Ekiti-East - Ekiti",
        "Ekiti-West - Ekiti",
        "Emure/Ise/Orun - Ekiti",
        "Gbonyin - Ekiti",
        "Ido/Osi - Ekiti",
        "Ijero - Ekiti",
        "Ikare - Ekiti",
        "Ikole - Ekiti",
        "Ilejemeje - Ekiti",
        "Irepodun-Ekiti - Ekiti",
        "Ise/Orun - Ekiti",
        "Moba - Ekiti",
        "Oye - Ekiti",
        "Akko - Gombe",
        "Balanga - Gombe",
        "Billiri - Gombe",
        "Dukku - Gombe",
        "Funakaye - Gombe",
        "Gombe - Gombe",
        "Kaltungo - Gombe",
        "Kwami - Gombe",
        "Nafada/Bajoga - Gombe",
        "Shomgom - Gombe",
        "Yamaltu/Delta - Gombe",
        "Aboh-Mbaise - Imo",
        "Ahiazu-Mbaise - Imo",
        "Ehime-Mbano - Imo",
        "Ezinihitte - Imo",
        "Ideato North - Imo",
        "Ideato South - Imo",
        "Ihitte/Uboma - Imo",
        "Ikeduru - Imo",
        "Isiala Mbano - Imo",
        "Isu - Imo",
        "Mbaitoli - Imo",
        "Ngor-Okpala - Imo",
        "Njaba - Imo",
        "Nkwerre - Imo",
        "Nwangele - Imo",
        "Obowo - Imo",
        "Oguta - Imo",
        "Ohaji/Egbema - Imo",
        "Okigwe - Imo",
        "Orlu - Imo",
        "Orsu - Imo",
        "Oru East - Imo",
        "Oru West - Imo",
        "Owerri - Imo",
        "Auyo - Jigawa",
        "Babura - Jigawa",
        "Biriniwa - Jigawa",
        "Birni Kudu - Jigawa",
        "Buji - Jigawa",
        "Dutse - Jigawa",
        "Gagarawa - Jigawa",
        "Garki - Jigawa",
        "Gumel - Jigawa",
        "Guri - Jigawa",
        "Gwaram - Jigawa",
        "Gwiwa - Jigawa",
        "Hadejia - Jigawa",
        "Jahun - Jigawa",
        "Kafin Hausa - Jigawa",
        "Kaugama Kazaure - Jigawa",
        "Kiri Kasamma - Jigawa",
        "Kiyawa - Jigawa",
        "Maigatari - Jigawa",
        "Malam Madori - Jigawa",
        "Miga - Jigawa",
        "Ringim - Jigawa",
        "Roni - Jigawa",
        "Sule-Tankarkar - Jigawa",
        "Taura - Jigawa",
        "Yankwashi - Jigawa",
        "Birni-Gwari - Kaduna",
        "Chikun - Kaduna",
        "Giwa - Kaduna",
        "Igabi - Kaduna",
        "Ikara - Kaduna",
        "jaba - Kaduna",
        "Jema'a - Kaduna",
        "Kachia - Kaduna",
        "Kaduna North - Kaduna",
        "Kaduna South - Kaduna",
        "Kagarko - Kaduna",
        "Kajuru - Kaduna",
        "Kaura - Kaduna",
        "Kauru - Kaduna",
        "Kubau - Kaduna",
        "Kudan - Kaduna",
        "Lere - Kaduna",
        "Makarfi - Kaduna",
        "Sabon-Gari - Kaduna",
        "Sanga - Kaduna",
        "Soba - Kaduna",
        "Zango-Kataf - Kaduna",
        "Zaria - Kaduna",
        "Ajingi - Kano",
        "Albasu - Kano",
        "Bagwai - Kano",
        "Bebeji - Kano",
        "Bichi - Kano",
        "Bunkure - Kano",
        "Dala - Kano",
        "Dambatta - Kano",
        "Dawakin Kudu - Kano",
        "Dawakin Tofa - Kano",
        "Doguwa - Kano",
        "Fagge - Kano",
        "Gabasawa - Kano",
        "Garko - Kano",
        "Garum - Kano",
        "Gaya - Kano",
        "Gezawa - Kano",
        "Gwale - Kano",
        "Gwarzo - Kano",
        "Kabo - Kano",
        "Kano Municipal - Kano",
        "Karaye - Kano",
        "Kibiya - Kano",
        "Kiru - Kano",
        "kumbotso - Kano",
        "Kunchi - Kano",
        "Kura - Kano",
        "Madobi - Kano",
        "Makoda - Kano",
        "Mallam - Kano",
        "Minjibir - Kano",
        "Nasarawa - Kano",
        "Rano - Kano",
        "Rimin Gado - Kano",
        "Rogo - Kano",
        "Shanono - Kano",
        "Sumaila - Kano",
        "Takali - Kano",
        "Tarauni - Kano",
        "Tofa - Kano",
        "Tsanyawa - Kano",
        "Tudun Wada - Kano",
        "Ungogo - Kano",
        "Warawa - Kano",
        "Wudil - Kano",
        "Bakori - Katsina",
        "Batagarawa - Katsina",
        "Batsari - Katsina",
        "Baure - Katsina",
        "Bindawa - Katsina",
        "Charanchi - Katsina",
        "Dan Musa - Katsina",
        "Dandume - Katsina",
        "Danja - Katsina",
        "Daura - Katsina",
        "Dutsi - Katsina",
        "Dutsin-Ma - Katsina",
        "Faskari - Katsina",
        "Funtua - Katsina",
        "Ingawa - Katsina",
        "Jibia - Katsina",
        "Kafur - Katsina",
        "Kaita - Katsina",
        "Kankara - Katsina",
        "Kankia - Katsina",
        "Katsina - Katsina",
        "Kurfi - Katsina",
        "Kusada - Katsina",
        "Mai'Adua - Katsina",
        "Malumfashi - Katsina",
        "Mani - Katsina",
        "Mashi - Katsina",
        "Matazuu - Katsina",
        "Musawa - Katsina",
        "Rimi - Katsina",
        "Sabuwa - Katsina",
        "Safana - Katsina",
        "Sandamu - Katsina",
        "Zango - Katsina",
        "Aleiro - Kebbi",
        "Arewa-Dandi - Kebbi",
        "Argungu - Kebbi",
        "Augie - Kebbi",
        "Bagudo - Kebbi",
        "Birnin Kebbi - Kebbi",
        "Bunza - Kebbi",
        "Dandi - Kebbi",
        "Fakai - Kebbi",
        "Gwandu - Kebbi",
        "Jega - Kebbi",
        "Kalgo - Kebbi",
        "Koko/Besse - Kebbi",
        "Maiyama - Kebbi",
        "Ngaski - Kebbi",
        "Sakaba - Kebbi",
        "Shanga - Kebbi",
        "Suru - Kebbi",
        "Wasagu/Danko - Kebbi",
        "Yauri - Kebbi",
        "Zuru - Kebbi",
        "Adavi - Kogi",
        "Ajaokuta - Kogi",
        "Ankpa - Kogi",
        "Bassa - Kogi",
        "Dekina - Kogi",
        "Ibaji - Kogi",
        "Idah - Kogi",
        "Igalamela-Odolu - Kogi",
        "Ijumu - Kogi",
        "Kabba/Bunu - Kogi",
        "Kogi - Kogi",
        "Lokoja - Kogi",
        "Mopa-Muro - Kogi",
        "Ofu - Kogi",
        "Ogori/Mangongo - Kogi",
        "Okehi - Kogi",
        "Okene - Kogi",
        "Olamabolo - Kogi",
        "Omala - Kogi",
        "Yagba East - Kogi",
        "Yagba West - Kogi",
        "Asa - Kwara",
        "Baruten - Kwara",
        "Edu - Kwara",
        "Ekiti - Kwara",
        "Ifelodun - Kwara",
        "Ilorin - Kwara",
        "Irepodun - Kwara",
        "Isin - Kwara",
        "Kaiama - Kwara",
        "Moro - Kwara",
        "Offa - Kwara",
        "Oke-Ero - Kwara",
        "Oyun - Kwara",
        "Pategi - Kwara",
        "Akwanga - Nassarawa",
        "Awe - Nassarawa",
        "Doma - Nassarawa",
        "Karu - Nassarawa",
        "Keana - Nassarawa",
        "Keffi - Nassarawa",
        "Kokona - Nassarawa",
        "Lafia - Nassarawa",
        "Nasarawa-Eggon - Nassarawa",
        "Obi-Nassarawa - Nassarawa",
        "Toto - Nassarawa",
        "Wamba - Nassarawa",
        "Agaie - Niger",
        "Agwara - Niger",
        "Bida - Niger",
        "Borgu - Niger",
        "Bosso - Niger",
        "Chanchaga - Niger",
        "Edati - Niger",
        "Gbako - Niger",
        "Gurara - Niger",
        "Katcha - Niger",
        "Kontagora - Niger",
        "Lapai - Niger",
        "Lavun - Niger",
        "Magama - Niger",
        "Mariga - Niger",
        "Mashegu - Niger",
        "Mokwa - Niger",
        "Muya - Niger",
        "Pailoro - Niger",
        "Rafi - Niger",
        "Rijau - Niger",
        "Shiroro - Niger",
        "Suleja - Niger",
        "Tafa - Niger",
        "Wushishi - Niger",
        "Akoko - Ondo",
        "Akure - Ondo",
        "Ese-Odo - Ondo",
        "Idanre - Ondo",
        "Ifedore - Ondo",
        "Ilaje - Ondo",
        "Ile-Oluji - Ondo",
        "Irele - Ondo",
        "Odigbo - Ondo",
        "Okeigbo - Ondo",
        "Okitipupa - Ondo",
        "Ondo East - Ondo",
        "Ondo West - Ondo",
        "Ose - Ondo",
        "Owo - Ondo",
        "Aiyedade - Osun",
        "Aiyedire - Osun",
        "Atakumosa East - Osun",
        "Atakumosa West - Osun",
        "Boluwaduro - Osun",
        "Boripe - Osun",
        "Ede North - Osun",
        "Ede South - Osun",
        "Egbedore - Osun",
        "Ife Central - Osun",
        "Ife East - Osun",
        "Ife North - Osun",
        "Ife South - Osun",
        "Ifedayo - Osun",
        "Ila - Osun",
        "Ilesha East - Osun",
        "Ilesha West - Osun",
        "Irepodun-Osun - Osun",
        "Irewole - Osun",
        "Isokan - Osun",
        "Iwo - Osun",
        "Obokun - Osun",
        "Odo-Otin - Osun",
        "Ola-Oluwa - Osun",
        "Olorunda - Osun",
        "Oriade - Osun",
        "Orolu - Osun",
        "Osogbo - Osun",
        "Barikin Ladi - Plateau",
        "Bassa-Plateau - Plateau",
        "Bokkos - Plateau",
        "Jos East - Plateau",
        "Jos North - Plateau",
        "Jos South - Plateau",
        "Kanam - Plateau",
        "Kanke - Plateau",
        "Langtang North - Plateau",
        "Langtang South - Plateau",
        "Mangu - Plateau",
        "Mikang - Plateau",
        "Pankshin - Plateau",
        "Qua'an Pan - Plateau",
        "Riyom - Plateau",
        "Shendam - Plateau",
        "Wase - Plateau",
        "Binji - Sokoto",
        "Bodinga - Sokoto",
        "Dange-shnsi - Sokoto",
        "Gada - Sokoto",
        "Gawabawa - Sokoto",
        "Goronyo - Sokoto",
        "Gudu - Sokoto",
        "Illela - Sokoto",
        "Isa - Sokoto",
        "kebbe - Sokoto",
        "Kware - Sokoto",
        "Rabah - Sokoto",
        "Sabon birni - Sokoto",
        "Shagari - Sokoto",
        "Silame - Sokoto",
        "Sokoto North - Sokoto",
        "Sokoto South - Sokoto",
        "Tambuwal - Sokoto",
        "Tqngaza - Sokoto",
        "Tureta - Sokoto",
        "Wamako - Sokoto",
        "Wurno - Sokoto",
        "Yabo - Sokoto",
        "Ardo-kola - Taraba",
        "Bali - Taraba",
        "Cassol - Taraba",
        "Donga - Taraba",
        "Gashaka - Taraba",
        "Ibi - Taraba",
        "Jalingo - Taraba",
        "Karin-Lamido - Taraba",
        "Kurmi - Taraba",
        "Lau - Taraba",
        "Sardauna - Taraba",
        "Takum - Taraba",
        "Ussa - Taraba",
        "Wukari - Taraba",
        "Yorro - Taraba",
        "Zing - Taraba",
        "Bade - Yobe",
        "Bursari - Yobe",
        "Damaturu - Yobe",
        "Fika - Yobe",
        "Fune - Yobe",
        "Geidam - Yobe",
        "Gujba - Yobe",
        "Gulani - Yobe",
        "Jakusko - Yobe",
        "Karasuwa - Yobe",
        "Karawa - Yobe",
        "Machina - Yobe",
        "Nangere - Yobe",
        "Nguru Potiskum - Yobe",
        "Tarmua - Yobe",
        "Yunusari - Yobe",
        "Yusufari - Yobe",
        "Anka - Zamfara",
        "Bakura - Zamfara",
        "Birnin Magaji - Zamfara",
        "Bukkuyum - Zamfara",
        "Bungudu - Zamfara",
        "Gummi - Zamfara",
        "Gusau - Zamfara",
        "Kaura-Zamfara - Zamfara",
        "Maradun - Zamfara",
        "Maru - Zamfara",
        "Namoda - Zamfara",
        "Shinkafi - Zamfara",
        "Talata Mafara - Zamfara",
        "Tsafe - Zamfara",
        "Zurmi - Zamfara"
    ];

    /**
     * Randomly returns a Nigerian state or county.
     *
     * @example 'Lagos'
     *
     * @return string
     */
    public static function county()
    {
        return static::randomElement(static::$county);
    }

    /**
     * Randomly returns a Nigerian region of a state.
     *
     * @example 'Ikeja'
     *
     * @return string
     */
    public static function region()
    {
        return static::randomElement(static::$regions);
    }
}
